version: '3'

services:
  database:
    build: ./database/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5342:5432"
    container_name: 'fw-database'
  backend:
    build: ./backend/
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "5222:5000"
    volumes:
      - ./backend/app:/app
    container_name: 'fw-backend'

  frontend:
    build: ./frontend/
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "4222:4200"
    volumes:
      - ./frontend/app:/app
    container_name: 'fw-frontend'

volumes:
  flask_volume:
    driver: local
