FROM postgres:latest


# docker run --name some-postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 -d 

# psql -U postgres
# \l - show all databases
# \c postgres - connect to specific database
# \dt - show all tables in this database
# CREATE TABLE friends(friend_id INT NOT NULL,name VARCHAR (255) UNIQUE NOT NULL)
# INSERT INTO public.friends(friend_id, name)VALUES(0, 'aga');
# SELECT * FROM friends;
# INSERT INTO words (word, translated_word) VALUES('cat', 'kot');
